# scenarios:
#   default:
#     insert: run driver=cql tags==phase:insert

bindings:
  id: ToUUID()  # Manually generated UUID for testing

ops:
  - name: insert
    tags:
      phase: insert
    stmt: >
      INSERT INTO ecommerce.product_views_by_user (id) 
      VALUES ({id});
    log: debug  # Enable debug logging to check the generated id
