global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:7070']
