apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: ns-pg-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: exporter
          image: bitnami/postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:postgres@postgres-service.ns-pg-cluster.svc.cluster.local:5432/postgres?sslmode=disable"
          ports:
            - containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  namespace: ns-pg-cluster
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187


# env:
#             - name: DATA_SOURCE_NAME
#               value: "postgresql://postgres:postgres@postgres-service.ns-pg-cluster.svc.cluster.local:5432/postgres?sslmode=disable"