apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ns-pg-cluster
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter-service:9187']


# static_configs:
#           - targets: ['postgres-exporter-service:9187']