version: '3.7'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    # user: cassandra  # Add this line to run as cassandra user
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_PASSWORD_SEEDER=yes
    ports:
      - "9042:9042"
      - "7199:7199"  # JMX metrics port
    volumes:
      - ./cassandra-jmx.yml:/etc/cassandra/jmx_exporter.yml  # Mount JMX config
    command: >
      cassandra -f -R -Dcassandra.jmx.remote.port=7199 -Dcassandra.jmx.remote.authenticate=false -Dcassandra.jmx.remote.ssl=false
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
