global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:7070']  # Cassandra JMX metrics
    metrics_path: /metrics  # Expose the Prometheus-compatible metrics
