{
 "title": "Confluent Open Source -DEV",
 "description": "Confluent Open Source Grafana Dashboard v5.2.3",
 "tags": [ "5.4.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(zookeeper_initlimit, release)"
   }
  ]
 },
 "panels": [
  {
   "title": "Producers & Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer Avg Batch Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kafka_producer_batch_size_avg{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer Records Consumed Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer OutGoing Bytes",
     "type": "graph",
     "description": "Average number of outgoing/incoming bytes per second. As with Kafka brokers, you will want to monitor your producer network throughput. Observing traffic volume over time is essential for determining whether you need to make changes to your network infrastructure. Monitoring producer network traffic will help to inform decisions on infrastructure changes, as well as to provide a window into the production rate of producers and identify sources of excessive traffic.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "kafka_producer_outgoing_byte_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer Bytes Consumed Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_bytes_consumed_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer Request Latency Avg",
     "type": "graph",
     "description": "The average request latency in ms. The average request latency is a measure of the amount of time between when KafkaProducer.send() was called until the producer receives a response from the broker.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "kafka_producer_request_latency_avg{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer Fetch Latency Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "kafka_consumer_fetch_latency_avg{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer Record Send Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kafka_producer_record_send_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer Record Error Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_record_error_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer Record Queue Time Avg",
     "type": "graph",
     "description": "The  amount  of  time  the  request  spends  in  queue  after  it  has  been  received  but before processing starts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "kafka_producer_record_queue_time_avg{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Kafka Producer Compression Rate Avg",
     "type": "graph",
     "description": "The average compression rate of record batches.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "kafka_producer_compression_rate_avg{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer Request Rate",
     "type": "graph",
     "description": "The request rate is the rate at which producers send data to brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "kafka_producer_request_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer Response Rate",
     "type": "graph",
     "description": "For producers, the response rate represents the rate of responses (per second) received from brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "kafka_producer_response_rate{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Producer I/O Wait Time",
     "type": "graph",
     "description": "Average length of time the I/O thread spent waiting for a socket (in ns)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "kafka_producer_io_wait_time_ns_avg{instance=~\".*sp-dev-broker.*\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers Online",
     "type": "singlestat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_leadercount{instance=~\".*sp-dev-broker.*\"})"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "singlestat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{instance=~\".*sp-dev-broker.*\"})"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "singlestat",
     "description": "Unclean leader election rate",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionenablerateandtimems{instance=~\".*sp-dev-broker.*\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "singlestat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_partitioncount{instance=~\".*sp-dev-broker.*\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "singlestat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{instance=~\".*sp-dev-broker.*\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "singlestat",
     "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{instance=~\".*sp-dev-broker.*\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka\",instance=~\".*sp-dev-broker.*\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\",instance=~\".*sp-dev-broker.*\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "kafka_network" }
     ]
    },
    {
     "title": "Byte Rate",
     "type": "graph",
     "description": "Byte Rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_brokertopicmetrics_bytesin_total{instance=~\".*sp-dev-broker.*\"})",
       "legendFormat": "Incoming Byte Rate"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{instance=~\".*sp-dev-broker.*\"})",
       "legendFormat": "Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Messages/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",instance=~\".*sp-dev-broker.*\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes in Per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",instance=~\".*sp-dev-broker.*\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes out Per Topic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",instance=~\".*sp-dev-broker.*\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Produce Request Rate",
     "type": "graph",
     "description": "Produce Request Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_producemessageconversions_total{instance=~\".*sp-dev-broker.*\"})",
       "legendFormat": "Total Produce Requests"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_failedproducerequests_total{instance=~\".*sp-dev-broker.*\"})",
       "legendFormat": "Failed Produce Requests"
      }
     ]
    },
    {
     "title": "Fetch Request Rate",
     "type": "graph",
     "description": "Fetch Request Rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"kafka\",instance=~\".*sp-dev-broker.*\",topic!=\"\"}[5m])",
       "legendFormat": "{{topic}}"
      },
      {
       "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=\"kafka\",instance=~\".*sp-dev-broker.*\",topic!=\"\"}[5m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Network Processor Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{instance=~\".*sp-dev-broker.*\"}*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Request Handler Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent{instance=~\".*sp-dev-broker.*\"}*100",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_metrics_connector_count{instance=~\".*sp-dev-connect.*:8080\"})"
      }
     ]
    },
    {
     "title": "Connector Startup Success Total",
     "type": "singlestat",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_metrics_connector_startup_success_total{instance=~\".*sp-dev-connect.*:8080\"})"
      }
     ]
    },
    {
     "title": "Connector Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of connector starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_metrics_connector_startup_failure_total{instance=~\".*sp-dev-connect.*:8080\"})"
      }
     ]
    },
    {
     "title": "Coordinator Assigned Tasks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_coordinator_assigned_tasks{instance=~\".*sp-dev-connect.*:8080\"})"
      }
     ]
    },
    {
     "title": "Task Startup Success Total",
     "type": "singlestat",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_metrics_connector_startup_success_total{instance=~\".*sp-dev-connect.*:8080\"})"
      }
     ]
    },
    {
     "title": "Task Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_metrics_task_startup_failure_total{instance=~\".*sp-dev-connect.*:8080\"})"
      }
     ]
    },
    {
     "title": "Connect Metrics: IO Avg Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_connect_metrics_connect_1_io_time_ns_avg{instance=~\".*sp-dev-connect.*:8080\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Incoming Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_metrics_connect_1_incoming_byte_rate{instance=~\".*sp-dev-connect.*:8080\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_metrics_connect_1_network_io_rate{instance=~\".*sp-dev-connect.*:8080\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka REST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka REST servers",
     "type": "singlestat",
     "description": "Number of Kafka REST servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_rest_jetty_metrics_connections_active{instance=~\".*sp-dev-schema-registry.*:8084\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(kafka_rest_jetty_metrics_connections_active{instance=~\".*sp-dev-schema-registry.*:8084\"})"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_rest_jetty_metrics_connections_opened_rate{instance=~\".*sp-dev-schema-registry.*:8084\"})"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_rest_jetty_metrics_connections_closed_rate{instance=~\".*sp-dev-schema-registry.*:8084\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent KSQL Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "KSQL Metrics: Bytes Consumed",
     "type": "graph",
     "description": "Total number of bytes consumed.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ksql_server_metrics_bytes_consumed_total"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Consumed",
     "type": "graph",
     "description": "Messages consumed per second.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ksql_server_metrics_messages_consumed_per_sec"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Messages Produced",
     "type": "graph",
     "description": "Messages produced per second.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ksql_server_metrics_messages_produced_per_sec"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Active Queries",
     "type": "graph",
     "description": "Number of active queries.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ksql_server_metrics_num_active_queries"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Idle Queries",
     "type": "graph",
     "description": "Number of idle queries.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ksql_server_metrics_num_idle_queries"
      }
     ]
    },
    {
     "title": "KSQL Metrics: Persistent Queries",
     "type": "graph",
     "description": "Number of persistent queries.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ksql_server_metrics_num_persistent_queries"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "singlestat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_schema_registry_jetty_metrics_connections_active{instance=~\".*sp-dev-schema-registry.*:8080\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_schema_registry_jetty_metrics_connections_active{instance=~\".*sp-dev-schema-registry.*:8080\"})"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_schema_registry_jetty_metrics_connections_opened_rate{instance=~\".*sp-dev-schema-registry.*:8080\"})"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_schema_registry_jetty_metrics_connections_closed_rate{instance=~\".*sp-dev-schema-registry.*:8080\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum Size",
     "type": "singlestat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(zookeeper_quorumsize{instance=~\".*sp-dev-zookeeper.*:8079\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "singlestat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(zookeeper_numaliveconnections{instance=~\".*sp-dev-zookeeper.*:8079\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(zookeeper_outstandingrequests{instance=~\".*sp-dev-zookeeper.*:8079\"})",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(zookeeper_inmemorydatatree_nodecount{instance=~\".*sp-dev-zookeeper.*:8079\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "singlestat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(zookeeper_inmemorydatatree_watchcount{instance=~\".*sp-dev-zookeeper.*:8079\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka\",instance=~\".*sp-dev-zoo.*\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\",instance=~\".*sp-dev-broker.*\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-zookeeper.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zookeeper_minrequestlatency{instance=~\".*sp-dev-zookeeper.*:8079\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zookeeper_avgrequestlatency{instance=~\".*sp-dev-zookeeper.*:8079\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zookeeper_maxrequestlatency{instance=~\".*sp-dev-zookeeper.*:8079\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}