apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ns-pg-cluster
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'postgres'
        static_configs:
          - targets: ['localhost:9187']

