apiVersion: v1
kind: Service
metadata:
  name: realtime-inventory-service
  namespace: ecommerce
spec:
  selector:
    app: realtime-inventory-service
  ports:
    - port: 3004
      targetPort: 3004
